### ISSUE TITLE
baseURL not respected in some cases

### ISSUE THREAD

**Issue by klapauciusisgreat** [Track3/hermit#14]
I have a server I'm running on AWS, where I use packetfilters to map incoming/outgoig packets on port 80 to localhost:8080.

So to hugo it looks like the server is on localhost:8080, but I can externally talk to http://AWS-IP:80.

So far so good. Now, if I put something like 
baseURL="http:/1.2.3.4/"

in config.toml, then many links are correctly mapped, but some (esp the ones in the footer, like index.xml) are still pointing to "locahost:8080"

Now, I can apparently fix this by starting hugo with extra parameters, such as

hugo serve -p 8080 --baseURL="http://1.2.3.4/" --appendPort=false

but it seems like a kludge. I have not dug into the code enough to know why the .Site.BaseUrl in themes/hermit/layouts/index.html does not work, and I have not tried other themes, so this could be general a hugo problem. But it would help to rule out that it's a theme problem, so any help diagnosing or reproducing this would be great!

Many thanks in advance.

**Comment by Track3** [comment]
`hugo server` is more intended for development, it expects you to use it at localhost. Without any flags, the `baseURL` set in the config are ignored, instead, default `http://localhost:1313` is used. `baseURL` will affect all absolute urls in the page, so if you really want to use hugo server in production, add a `--baseUrl` argument in the server command seems to be the only way, or…try to use relative URL for every link……

**Comment by gusanmaz** [comment]
I want to serve my blog under [localhost:8086/blog/](localhost:8086/blog/). First I set my baseURL to "[localhost:8087/blog/](localhost:8086/blog/)"
in config.toml and then run hugo. I expected links from html files have /blog/ prefix but they have not. For instance javascript file refered from index.html manifest itself like `<script src="/js/main.min.xxxxxxx>` instead of `<script src="/blog/js/main.min.xxxxx>`. When I run `hugo -b "localhost:8087/blog/`" I get same output. When I switched to a different theme I didn't experience this issue. 

I wonder if something is broken about the theme or I am missing something since I am not very familiar with Hugo.

Many thanks in advance!

**Comment by gusanmaz** [comment]
It seems like changing localhost:8087/blog/ to http://localhost:8087/blog/ solves the issue.

**Comment by Track3** [comment]
@gusanmaz Good to know that. I tried `//localhost:8087/blog/` also work.

**Comment by Track3** [comment]
There's nothing we can do with this theme, so I'm going to close this issue for now.
