### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by graemer957** [Track3/hermit#22]
Hi @Track3, firstly, thank you for creating this excellent theme. Finding it made my decision to use Hugo for my site easy 😀

Today I spent some time adding a `Content-Security-Policy` for my [website](https://sigma957.net). I blogged about the steps I took [here](https://sigma957.net/posts/content-security-policy/), but in summary:

* In order to allow `<script>let haveHeader = true;</script>` to execute I had to add the hash `sha256-AnD4MU8ryLQfUOxyB+K8iDV82R0rMK6os4wCSP8Cqqo=`
* Similarly, to allow `<script>let haveHeader = false;</script>` to execute I had to add the hash `sha256-mzxFK7/AUlIhalqxiKcyRO9mSXWeALlmGjRumxphi9M=`
* I saw an issue with the inline style applied in the HTML `<div id="mobile-menu" class="animated fast" style="display: none;">`. The suggested hash Chrome gave me (`sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog=`) did not work, so I had to add `unsafe-inline`

I see Hugo adds an `integrity` attribute to other tags, but I am not sure if that only works if they are not inline?

Here is the version information for the version of Hugo I am using:

> Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown

I have only just started to use Hugo, so please forgive me if I have missed something. Thanks in advance.

**Comment by Track3** [comment]
My javascript is very bad, as you can see. This inline script just looks nasty.

I added a commit just now, removed this inline script, now main.js can check if the header exists by itself.

**Comment by Track3** [comment]
Inline JS is solved, let's talk about inline CSS. From what I see ,it's impossible not to use inline css because it's dynamicly generated, like the background image url, if you move it to the external css, that means some page have to load a different css, that's a nightmare for caching.

Hugo has the ability to get resources from string, and resources can be fingerprinted. I'm not sure where to put the hash. Here's what I tried with `layouts/posts/single.html`:

```html
{{- with .Params.featuredImg }}
{{- $string := printf "background-image: url('%s');" . | safeCSS }}
{{- $temp := $string | resources.FromString "temp.css" | resources.Fingerprint }}
<div id="bg-img" class="bg-img" style="{{ $string }}" {{ printf "integrity=%q" $temp.Data.Integrity | safeHTMLAttr }} onclick="showContent()"></div>
{{- end }}
```
I added an integrity attribute to that div, `$temp.Data.Integrity` is the hash.

**Comment by Track3** [comment]
`display: none` style can be easily moved into style.scss `#mobile-menu {}` block (about line 251). But the problem is, that's not the only place the theme uses inline style, you haven't use that background image feature yet, so that didn't appear. If you are never going to use this feature, then it will all be fine.

**Comment by graemer957** [comment]
I understand @Track3. No you are right, I have not used the background image feature yet. Sorry I cannot be more useful with suggestions, but I am happy to help test.

**Comment by Track3** [comment]
I wonder if I put inline css inside a `<style>` element, then I get the hash by Hugo, will something like this work?
```html
<style integrity="sha256-xxxx">
.bg-img {
  background-image: url();
}
</style>
```

**Comment by graemer957** [comment]
I am not sure if the `integrity` attribute works for that: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by Track3** [comment]
This is what I learned for now:

In CSP Level 2, there're two ways to make inline style or script work, Nonces and Hashes. Nonces seems to need every request have a ramdom value, the header have to match it, so header need to be dynamicly added. This is impossible for a static site. Hashes need you to add header by hand, which seems to be the only solution to this.

I also learned hashes doesn't work with inline code like this:
```html
<span style="color:red;">demo</span>
<span onclick="alert(0);">demo</span>
```
but works with this:
```html
<style>span {color:red;}</style>
<script>alert(0);</script>
```
That's why that hash chrome gave you doesn't work. Now I removed all inline style and script inside that `.bg-img` div, so this should work now. If you add background image in the future, you need to add hashes by hand.

**Comment by Track3** [comment]
> even thought I was not using the background image feature the following HTML was still being generated, and failing

You should add this hash chrome gave you by hand in nginx.conf just like dealing with that `<script>let haveHeader = true;</script>` Because there's no way I can do to totally remove this. When you start to use background image, this is a different value, you should also add it then.

> Does not seem like any changes to assets/scss/style.scss are being picked up when I rebuild site!

If you didn't use the extended version of Hugo, every time the theme has style updates, you should probably delete your site's resources folder before build.

**Comment by graemer957** [comment]
> You should add the hash Chrome gave you by hand in nginx.conf just like dealing with that `<script>let haveHeader = true;</script>` Because there's nothing I can do to totally remove this. When you start to use background image, this is a different value, you should also add it then.

Understood, thanks.

> If you didn't use the extended version of Hugo, every time the theme has style updates, you should probably delete your site's resources folder before build. It's recommended to use Hugo extended version at development environment.

I was not aware of this. Thanks for heads up. Removing the `resources` directory to force recreation fixed what I was seeing.

My `Content-Security-Policy` is now very clean. Thank you for the help @Track3.

**Comment by shibumi** [comment]
@graemer957 Hi, I am using CSP as well for my blog and I changed from hello-world-ng to hermit, because of speed. Hermit works fine for me, just my index file looks odd. There is no menu and no social icons.. just the footer... do you have any idea?

https://nullday.de/

![](https://paste.xinu.at/6Ux/)
