### ISSUE TITLE
Link text is broken at any character on Chromium

### ISSUE THREAD

**Issue by marceloneil** [Track3/hermit#32]
On Chromium (Firefox seems to be fine), link text is broken such that the text is difficult to read, which affects mobile users especially. This line seems to be the culprit:
https://github.com/Track3/hermit/blob/885bf2c8711d1b4881a849bbafe26efc7626f66b/assets/scss/_predefined.scss#L23

This is what occurs when we use `word-break: break-all;` (current behaviour for Chromium)
![broken](https://user-images.githubusercontent.com/6353492/51281672-214b4e80-19b1-11e9-8879-1d4a9cc17594.png)

This is what occurs when we use `word-break: normal;` (expected behaviour, what happens on Firefox)
![fixed](https://user-images.githubusercontent.com/6353492/51281671-20b2b800-19b1-11e9-9b83-4fefb700de3f.png)

`word-break: break-all;` has some other occurances in the stylesheets (for code and links on the 404 page I think), although I'm not sure if they work as intended or not

**Comment by Track3** [comment]
I use `word-break: break-all;` because  when a link text is very long and no spaces in it, such as an url, in Chrome, and when the page width is narrow, link text will overflow, horizontal scroll bar appears. This is what happened with Chrome, without `word-break: break-all;`:

<img width="273" alt="1" src="https://user-images.githubusercontent.com/34504964/51310804-67241780-1a82-11e9-8408-323aa98fab0e.PNG">

In Firefox everything's fine. I did the same thing with `code` elements.

I'm not very familiar with `word-break` and `word-wrap` properties, so I can't tell what's the best solution to this.

**Comment by marceloneil** [comment]
Hmm that is tricky, the current behaviour is certainly better for long links than using `word-break: normal;`. I don't know if hyphenating would be a good idea either, as it might read like the hyphens are in the url itself.

I'll do a bit more reading into `word-break`, `word-wrap` and `overflow-wrap` properties, although it seems like this is just a Chromium issue - Firefox is doing this a lot better.

**Comment by zemien** [comment]
I agree the issue is how individual browsers render the CSS. 

I did some tests on my [own page](https://www.coderfrontline.com/humidity-monitor-winter-of-xamarin-2017/) and I feel switching from break-all to break-word will be an improvement. Links with spaces, hyphens, and other wrap-able characters will break normally, while super long words will break at any character as it currently does.

![image](https://user-images.githubusercontent.com/8407032/51583762-de502480-1f36-11e9-8449-109e5af23fe2.png)

**Comment by marceloneil** [comment]
Hmm that does look better. `break-word` has the same effect as `break-all` using Chromium 71 on my system, but if it fixes at least some browsers I'm all for it.

**Comment by zemien** [comment]
I read somewhere that break-all might be better for CJK languages. I don’t
write Chinese Japanese or Korean so I can’t test the breaking behaviour on
those. But it sure looks fine for Roman alphabets.
