### ISSUE TITLE
Google Analytics Not Working

### ISSUE THREAD

**Issue by dancwilliams** [Track3/hermit#35]
Hello,

First, great theme!  I only seem to be running into a single issue and I have done a bit of troubleshooting and cannot run it down.

First, the details on my site:

[Published Site](https://dancwilliams.com)
[Github Repo](https://github.com/dancwilliams/dancwilliams)
Netlify for hosting and deployment

Now, to the issue:

I put the site up and noticed that google analytics was not collecting stats.  I checked my config and everything looked good.  I walked the rendering of the site and it looks like the `analytics.html` partial gets called, but for some reasons the Google Analytics template is not being rendered.’

I am sure it is something basic that I am overlooking, but I need another set of eyes.  Any assistance would be greatly appreciated.

Thanks!

**Comment by Track3** [comment]
I noticed in your github repo, theme hasn't update. This bug is fixed in #31.

Here's the line that didn't work: 
https://github.com/dancwilliams/dancwilliams/blob/cd9a9fdeae71868ab6a0986a8c360e201d3bd115/themes/hermit/layouts/_default/baseof.html#L37

It should be `{{- partial "analytics.html" . }}`.

**Comment by dancwilliams** [comment]
Thanks!!
