### ISSUE TITLE
The background is white in Chrome but works in Firefox

### ISSUE THREAD

**Issue by karanveersp** [Track3/hermit#46]
I just got started using Hugo and followed the quickstart tutorial. I installed the Hermit theme by moving the extracted folder from the .zip file downloaded from Github and moving the config.toml file from the exampleSite folder to my site's root folder. 

I don't see any errors in the console when I navigate to localhost:1313. I don't know why it works in firefox just fine but not in Chrome. 
![capture](https://user-images.githubusercontent.com/7011511/52166188-f31b7d80-26d7-11e9-9dd9-1c84eac50cac.PNG)

**Comment by Track3** [comment]
I have no idea how this could happen, I can't reproduce this. If firefox is fine, but Chrome doesn't, I suspect this is caused by some Chrome Extensions. You can use Chrome DevTools (by pressing <kbd>F12</kbd>), see the "Elements" tab, click `<html lang="…">` tag, see the style section on the right, pay attention to `background` property.

![ss](https://user-images.githubusercontent.com/34504964/52171908-5375f200-27a0-11e9-9fe7-298170ece488.png)

**Comment by karanveersp** [comment]
Yeah, it turned out to be a chrome extension (Screen Shader) although it was turned off. Once I uninstalled it, the page loaded with the correct background color. 
Thanks
