### ISSUE TITLE
Support discourse forum for comments.

### ISSUE THREAD

**Issue by fire** [Track3/hermit#67]
It should be possible to use discourse as a commenting system.

**Comment by Track3** [comment]
Obviously, it's impossible for this theme to support every commenting systems, because there will always be some commenting systems you didn't know. I prefer only to support most commonly used one out of the box, it's encouraged to override theme's `layouts/partials/comments.html` if you want to used something other than disqus. For me, it's so much flexible than just an option in the config file.

**Comment by Track3** [comment]
Close this for now, anyone would like to have this feature, feel free to submit a pull request or just add more comments.
