### ISSUE TITLE
Missing Menu and social icons on main page

### ISSUE THREAD

**Issue by shibumi** [Track3/hermit#83]
I have the following website: https://github.com/shibumi/nullday.de/tree/hermit

when I serve it via hugo locally everything works fine, but when I serve it via nginx it shows hermit, but without main page + social icons (see https://nullday.de) any idea?

**Comment by shibumi** [comment]
I have tracked this issue down.. and I think it's a bug in hugo:

https://github.com/gohugoio/hugo/issues/6096

**Comment by shibumi** [comment]
Ok I have found the issue... it happens only when I have `categories = ""` in my configuration file.

Yes, I should possibly use your configuration and modify it earlier instead of using the configuration for the other theme and just starting to use it with your theme.. but I still think this shouldn't really happen oO your theme should ignore such `categories = ""` option or at least trigger a warning message or something. I wasted several days with looking for this bug, lol.

**Comment by Track3** [comment]
Did you see the the pinned issue? I should have replied to you earlier but a little bit busy these days.

This issue is bugging me for months as well. I still think it's a bug of Hugo, or in another point of view , since `categories = ""` is a incorrect config, Hugo should handle this itself, not in the theme level. I don't know why so many people (include myself) use `categories = ""` to disable categories, the docs doesn't do it like this: https://gohugo.io/content-management/taxonomies#example-removing-default-taxonomies

**Comment by shibumi** [comment]
oh my god.. I am so blind. No I didn't see the pinned issue, I was just searching the issues with words like `menu disappeared` or others. It confused me a lot, because when I did `hugo serve` it worked fine, but when I generated the content the content was different.
